[general]
import = [
  "theme.toml",
  "keybinds.toml",
]

[window]
resize_increments = true
option_as_alt = "OnlyLeft"

[font]
size = 11.75
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font Mono", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "Bold Italic" }

